name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Run tests in an Alpine Linux container
    - name: Run tests in Alpine
      uses: addnab/docker-run-action@v3
      with:
        image: python:3.9-alpine
        options: --entrypoint ""  # Reset entrypoint if needed
        run: |
          apk add --no-cache gcc musl-dev  # Install build dependencies
          pip install -r requirements.txt
          pytest
